"""Tests for tools/goof_rom.py and tools/validate_rom.py.

Synthetic tests use generated bytes and temporary descriptors only; no ROM
bytes are stored anywhere.  Integration tests read the user's own ROM when
GOOF_TEST_ROM points to it and are skipped otherwise:

    GOOF_TEST_ROM=/path/to/GOOFT_USA.sfc python3 -m unittest discover -s tests -v
"""

from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest

TOOLS = Path(__file__).resolve().parent.parent / "tools"
sys.path.insert(0, str(TOOLS))

import goof_rom  # noqa: E402
from goof_rom import RomError  # noqa: E402

CLI = TOOLS / "validate_rom.py"
CANONICAL_SIZE = 4096
HEADER_OFFSET = 0x7C0  # scaled-down stand-in for LoROM $7FC0


def synthetic_rom(seed: int = 1) -> bytes:
    """Deterministic pseudo-random bytes with a plausible internal header."""
    out = bytearray()
    block = seed.to_bytes(4, "little")
    while len(out) < CANONICAL_SIZE:
        block = hashlib.sha256(block).digest()
        out += block
    rom = out[:CANONICAL_SIZE]
    rom[HEADER_OFFSET + 0x15] = 0x30
    rom[HEADER_OFFSET + 0x17] = 0x09
    rom[HEADER_OFFSET + 0x19] = 0x01
    rom[HEADER_OFFSET + 0x1B] = 0x00
    return bytes(rom)


def file_state(path: Path) -> tuple:
    st = path.stat()
    return hashlib.sha256(path.read_bytes()).hexdigest(), st.st_size, st.st_mtime_ns


class Fixture(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory(prefix="goof_rom_test_")
        self.tmp = Path(self._tmp.name)
        self.rom = synthetic_rom()
        self.descriptor_path = self.write_descriptor()
        self.descriptor = goof_rom.load_descriptor(self.descriptor_path)

    def tearDown(self):
        self._tmp.cleanup()

    def write_descriptor(self, name="descriptor.json", **overrides) -> Path:
        body = {
            "schema_version": 1, "game": "Synthetic", "region": "TEST",
            "revision": 0, "mapping": "lorom", "canonical_size": CANONICAL_SIZE,
            "sha256": hashlib.sha256(self.rom).hexdigest(),
            "md5": hashlib.md5(self.rom).hexdigest(),
            "header_policy": "strip_exact", "accepted_header_size": 512,
            "internal_header": {"offset": HEADER_OFFSET, "map_mode": 0x30,
                                "rom_size_code": 0x09, "region_code": 0x01,
                                "version": 0x00},
        }
        body.update(overrides)
        path = self.tmp / name
        path.write_text(json.dumps(body), encoding="utf-8")
        return path

    def write(self, name: str, data: bytes) -> Path:
        path = self.tmp / name
        path.write_bytes(data)
        return path

    def run_cli(self, *args: str) -> subprocess.CompletedProcess:
        return subprocess.run([sys.executable, str(CLI), *args],
                              capture_output=True, text=True, timeout=60)

    def assertRejected(self, path, code, kind=goof_rom.ROM_MISMATCH):
        with self.assertRaises(RomError) as ctx:
            goof_rom.load_and_validate_rom(path, self.descriptor)
        self.assertEqual(ctx.exception.code, code)
        self.assertEqual(ctx.exception.kind, kind)
        return ctx.exception


class InputErrors(Fixture):
    def test_missing_path(self):
        self.assertRejected(self.tmp / "absent.sfc", "not_found", goof_rom.INPUT_ERROR)

    def test_directory(self):
        self.assertRejected(self.tmp, "is_directory", goof_rom.INPUT_ERROR)

    @unittest.skipIf(os.name == "nt" or (hasattr(os, "geteuid") and os.geteuid() == 0),
                     "permission bits not enforceable here")
    def test_unreadable(self):
        path = self.write("locked.sfc", self.rom)
        path.chmod(0)
        try:
            self.assertRejected(path, "unreadable", goof_rom.INPUT_ERROR)
        finally:
            path.chmod(0o600)


class Identity(Fixture):
    def test_exact_unheadered_accepted(self):
        path = self.write("good.sfc", self.rom)
        result = goof_rom.load_and_validate_rom(path, self.descriptor)
        self.assertEqual(result.canonical, self.rom)
        self.assertFalse(result.header_present)
        self.assertEqual(result.raw_size, CANONICAL_SIZE)

    def test_wrong_size(self):
        for size in (0, 1, CANONICAL_SIZE - 1, CANONICAL_SIZE + 1):
            with self.subTest(size=size):
                path = self.write(f"size{size}.sfc", self.rom[:size] if size <= CANONICAL_SIZE
                                  else self.rom + b"\0")
                err = self.assertRejected(path, "size")
                self.assertEqual(err.details["accepted_raw_sizes"],
                                 [CANONICAL_SIZE, CANONICAL_SIZE + 512])

    def test_wrong_hash_correct_size(self):
        bad = bytearray(self.rom)
        bad[0] ^= 0xFF
        err = self.assertRejected(self.write("bad.sfc", bytes(bad)), "sha256")
        self.assertTrue(err.details["internal_header_matches"])
        self.assertNotEqual(err.details["observed_sha256"], self.descriptor.sha256)

    def test_other_rom_reports_header_mismatch(self):
        other = synthetic_rom(seed=2)
        err = self.assertRejected(self.write("other.sfc", other[:HEADER_OFFSET] + bytes(64)
                                             + other[HEADER_OFFSET + 64:]), "sha256")
        self.assertFalse(err.details["internal_header_matches"])

    def test_oversized_file_not_fully_read(self):
        path = self.tmp / "big.bin"
        with path.open("wb") as handle:
            handle.truncate(64 * 1024 * 1024)  # sparse where supported
        err = self.assertRejected(path, "size")
        self.assertIn("raw_size_at_least", err.details)


class CopierHeader(Fixture):
    def test_exact_header_stripped(self):
        path = self.write("headered.smc", bytes(512) + self.rom)
        result = goof_rom.load_and_validate_rom(path, self.descriptor)
        self.assertTrue(result.header_present)
        self.assertEqual(result.header_size, 512)
        self.assertEqual(result.raw_size, CANONICAL_SIZE + 512)
        self.assertEqual(result.canonical, self.rom)

    def test_header_content_is_not_trusted_for_identity(self):
        path = self.write("headered2.smc", b"\xAA" * 512 + self.rom)
        self.assertTrue(goof_rom.load_and_validate_rom(path, self.descriptor).header_present)

    def test_headered_wrong_payload(self):
        bad = bytearray(self.rom)
        bad[-1] ^= 1
        self.assertRejected(self.write("hbad.smc", bytes(512) + bytes(bad)), "sha256")

    def test_malformed_header_sizes(self):
        # 256 and 511/513 are near misses; 1024 is a double header; the last
        # case satisfies the "size % 1024 == 512" heuristic but is rejected
        # because only the exact size is accepted.
        cases = {"h256": bytes(256) + self.rom, "h511": bytes(511) + self.rom,
                 "h513": bytes(513) + self.rom, "h1024": bytes(1024) + self.rom,
                 "heuristic": bytes(512) + self.rom + self.rom}
        for name, data in cases.items():
            with self.subTest(name):
                self.assertRejected(self.write(name + ".smc", data), "size")

    def test_policy_reject(self):
        desc = goof_rom.load_descriptor(
            self.write_descriptor("reject.json", header_policy="reject"))
        with self.assertRaises(RomError) as ctx:
            goof_rom.load_and_validate_rom(
                self.write("h.smc", bytes(512) + self.rom), desc)
        self.assertEqual(ctx.exception.code, "size")


class Descriptor(Fixture):
    def test_real_descriptor_loads(self):
        desc = goof_rom.load_descriptor()
        self.assertEqual(desc.mapping, "lorom")
        self.assertEqual(desc.header_policy, "strip_exact")
        self.assertEqual(desc.accepted_raw_sizes,
                         (desc.canonical_size, desc.canonical_size + 512))

    def test_bad_descriptors(self):
        cases = {
            "policy": {"header_policy": "guess"},
            "sha": {"sha256": "ABC"},
            "type": {"canonical_size": "524288"},
            "bool": {"canonical_size": True},
            "schema": {"schema_version": 2},
            "mapping": {"mapping": "hirom"},
        }
        for name, override in cases.items():
            with self.subTest(name):
                with self.assertRaises(RomError) as ctx:
                    goof_rom.load_descriptor(self.write_descriptor(name + ".json", **override))
                self.assertEqual(ctx.exception.kind, goof_rom.DESCRIPTOR_ERROR)

    def test_missing_descriptor(self):
        with self.assertRaises(RomError) as ctx:
            goof_rom.load_descriptor(self.tmp / "none.json")
        self.assertEqual(ctx.exception.code, "descriptor_missing")


class Cli(Fixture):
    def test_pass_text(self):
        path = self.write("good.sfc", self.rom)
        proc = self.run_cli(str(path), "--descriptor", str(self.descriptor_path))
        self.assertEqual(proc.returncode, 0, proc.stdout + proc.stderr)
        self.assertIn("SUPPORTED ROM: PASS", proc.stdout)

    def test_fail_exit_codes_without_traceback(self):
        bad = self.write("bad.sfc", bytes(CANONICAL_SIZE))
        cases = [([str(bad)], 1), ([str(self.tmp / "absent")], 3),
                 ([str(self.tmp)], 3), ([], 2)]
        for args, code in cases:
            with self.subTest(args=args):
                proc = self.run_cli(*args, "--descriptor", str(self.descriptor_path))
                self.assertEqual(proc.returncode, code)
                self.assertNotIn("Traceback", proc.stdout + proc.stderr)
                if code != 2:
                    self.assertIn("SUPPORTED ROM: FAIL", proc.stdout)
        proc = self.run_cli(str(bad), "--descriptor", str(self.tmp / "none.json"))
        self.assertEqual(proc.returncode, 4)
        self.assertNotIn("Traceback", proc.stdout + proc.stderr)

    def test_json_output(self):
        path = self.write("headered.smc", bytes(512) + self.rom)
        proc = self.run_cli(str(path), "--json", "--descriptor", str(self.descriptor_path))
        self.assertEqual(proc.returncode, 0)
        report = json.loads(proc.stdout)
        self.assertEqual(report["valid"], True)
        self.assertEqual(report["header_present"], True)
        self.assertEqual(report["raw_size"], CANONICAL_SIZE + 512)
        self.assertEqual(report["canonical_size"], CANONICAL_SIZE)
        self.assertEqual(report["canonical_sha256"], self.descriptor.sha256)

        proc = self.run_cli(str(self.write("bad.sfc", bytes(10))), "--json",
                            "--descriptor", str(self.descriptor_path))
        self.assertEqual(proc.returncode, 1)
        report = json.loads(proc.stdout)
        self.assertEqual((report["valid"], report["error_code"]), (False, "size"))

    def test_output_does_not_leak_rom_bytes(self):
        path = self.write("good.sfc", self.rom)
        proc = self.run_cli(str(path), "--json", "--descriptor", str(self.descriptor_path))
        self.assertLess(len(proc.stdout), 2048)
        self.assertNotIn(self.rom[:16].hex(), proc.stdout)

    def test_input_not_mutated(self):
        for name, data in (("good.sfc", self.rom), ("hdr.smc", bytes(512) + self.rom),
                           ("bad.sfc", bytes(CANONICAL_SIZE))):
            with self.subTest(name):
                path = self.write(name, data)
                before = file_state(path)
                self.run_cli(str(path), "--descriptor", str(self.descriptor_path))
                self.run_cli(str(path), "--json", "--descriptor", str(self.descriptor_path))
                self.assertEqual(file_state(path), before)
        self.assertEqual(sorted(p.name for p in self.tmp.iterdir()),
                         ["bad.sfc", "descriptor.json", "good.sfc", "hdr.smc"])


USER_ROM = os.environ.get("GOOF_TEST_ROM")


@unittest.skipUnless(USER_ROM, "set GOOF_TEST_ROM to the user's ROM to run")
class UserRomIntegration(unittest.TestCase):
    """Reads the user's ROM in place; never copies or writes it."""

    def test_supported_rom_passes_unchanged(self):
        path = Path(USER_ROM)
        before = file_state(path)
        desc = goof_rom.load_descriptor()
        result = goof_rom.load_and_validate_rom(path, desc)
        self.assertFalse(result.header_present)
        self.assertEqual(result.canonical_sha256, desc.sha256)
        self.assertEqual(result.canonical_md5, desc.md5)
        proc = subprocess.run([sys.executable, str(CLI), str(path), "--json"],
                              capture_output=True, text=True, timeout=60)
        self.assertEqual(proc.returncode, 0)
        self.assertTrue(json.loads(proc.stdout)["valid"])
        self.assertEqual(file_state(path), before)

    def test_internal_header_matches_descriptor(self):
        desc = goof_rom.load_descriptor()
        result = goof_rom.load_and_validate_rom(USER_ROM, desc)
        ih = desc.internal_header
        block = result.canonical[ih.offset:ih.offset + 32]
        self.assertEqual((block[0x15], block[0x17], block[0x19], block[0x1B]),
                         (ih.map_mode, ih.rom_size_code, ih.region_code, ih.version))

    def test_headered_form_in_memory(self):
        # Built in memory only: the headered variant never touches disk.
        desc = goof_rom.load_descriptor()
        canonical = goof_rom.load_and_validate_rom(USER_ROM, desc).canonical
        result = goof_rom.validate_rom_bytes(bytes(512) + canonical, desc)
        self.assertTrue(result.header_present)
        self.assertEqual(result.canonical_sha256, desc.sha256)

    def test_modified_copy_rejected_in_memory(self):
        desc = goof_rom.load_descriptor()
        data = bytearray(goof_rom.load_and_validate_rom(USER_ROM, desc).canonical)
        data[0x1000] ^= 0xFF
        with self.assertRaises(RomError) as ctx:
            goof_rom.validate_rom_bytes(bytes(data), desc)
        self.assertEqual(ctx.exception.code, "sha256")
        self.assertTrue(ctx.exception.details["internal_header_matches"])


if __name__ == "__main__":
    unittest.main()
