#!/usr/bin/env python3
"""One-command setup: check prerequisites -> validate ROM -> generate -> build
-> prepare the playable bundle in dist/.

Normally run through the wrappers in the repository root:

    ./setup_linux.sh /path/to/rom.sfc          (Linux)
    setup_windows.bat C:\\path\\to\\rom.sfc       (Windows)

Direct use:

    python3 tools/goof_setup.py [ROM] [--jobs N]
    python3 tools/goof_setup.py --clean

ROM may be omitted when exactly one *.sfc / *.smc file sits in the repository
root or in a rom/ folder inside it.  The ROM is only read.

Writes only build/ and dist/ inside the repository (both ignored by git):

    build/   generated C, CMake output (see tools/goof_build.py)
    dist/    GoofTroopRecomp[.exe], canonical.sfc, run_game.sh | run_game.bat
             (Windows: SDL2.dll and any other non-system DLL the player needs)

Exit codes: 0 ok; 2 usage; 30 prerequisite missing; 31 ROM not found or
ambiguous; 32 refused to remove an unexpected directory; 33 bundle failed;
otherwise the exit code of validate_rom.py / goof_build.py.
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import re
import shutil
import stat
import subprocess
import sys

sys.dont_write_bytecode = True
TOOLS = Path(__file__).resolve().parent
REPO = TOOLS.parent
sys.path.insert(0, str(TOOLS))

WINDOWS = os.name == "nt"
BUILD = REPO / "build"
DIST = REPO / "dist"
EXE_NAME = "GoofTroopRecomp.exe" if WINDOWS else "GoofTroopRecomp"
BUILT_EXE = BUILD / "cmake" / "frontend" / ("GoofTroopRecomp.exe" if WINDOWS else "goof_recomp")
CANONICAL = BUILD / "generated" / "rom" / "canonical.sfc"
LAUNCHER = "run_game.bat" if WINDOWS else "run_game.sh"
SETUP_CMD = "setup_windows.bat" if WINDOWS else "./setup_linux.sh"
ROM_EXAMPLE = "C:\\path\\to\\rom.sfc" if WINDOWS else "/path/to/rom.sfc"
ROM_SUFFIXES = (".sfc", ".smc")

EXIT_PREREQ, EXIT_ROM, EXIT_CLEAN, EXIT_BUNDLE = 30, 31, 32, 33

RUN_SH = """#!/bin/sh
# Generated by tools/goof_setup.py -- starts the game from this folder.
here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd) || exit 1
for f in GoofTroopRecomp canonical.sfc; do
  if [ ! -f "$here/$f" ]; then
    echo "Missing $here/$f -- run ./setup_linux.sh /path/to/rom.sfc again." >&2
    exit 1
  fi
done
exec "$here/GoofTroopRecomp" "$here/canonical.sfc" "$@"
"""

RUN_BAT = """@echo off
rem Generated by tools/goof_setup.py -- starts the game from this folder.
setlocal
set "HERE=%~dp0"
if not exist "%HERE%GoofTroopRecomp.exe" goto missing
if not exist "%HERE%canonical.sfc" goto missing
if not exist "%HERE%SDL2.dll" goto missing
"%HERE%GoofTroopRecomp.exe" "%HERE%canonical.sfc" %*
exit /b %ERRORLEVEL%
:missing
echo The game bundle in "%HERE%" is incomplete.
echo Run setup_windows.bat with your ROM again.
if not defined GOOF_NO_PAUSE pause
exit /b 1
"""


def say(text: str = "") -> None:
    print(text, flush=True)


def fail(code: int, title: str, lines: list[str]) -> int:
    print(f"\nSETUP: FAIL -- {title}", file=sys.stderr)
    for line in lines:
        print(f"  {line}", file=sys.stderr)
    return code


# --- clean ------------------------------------------------------------------

def remove_generated(path: Path, markers: tuple[str, ...]) -> str | None:
    """Remove build/ or dist/.  Only ever called with those two fixed paths;
    refuses anything that is a link, is not directly inside the repository or
    does not look like what this tool creates.  Returns an error text."""
    if not path.exists() and not path.is_symlink():
        return None
    if path.is_symlink() or not path.is_dir():
        return f"{path} is not a plain directory; remove it yourself"
    if path.parent != REPO or path.name not in ("build", "dist"):
        return f"{path} is not a generated directory of this repository"
    entries = [e.name for e in path.iterdir()]
    if entries and not any(m in entries for m in markers):
        return (f"{path} does not look like something setup created "
                f"(contains: {', '.join(sorted(entries)[:5])}); remove it yourself")
    shutil.rmtree(path)
    return None


def clean() -> int:
    for path, markers in ((BUILD, ("generated", "cmake", "host-tests", "gates")),
                          (DIST, (EXE_NAME, "canonical.sfc", LAUNCHER))):
        existed = path.exists()
        err = remove_generated(path, markers)
        if err:
            return fail(EXIT_CLEAN, "clean refused", [err])
        say(f"{'removed' if existed else 'absent '}  {path.name}/")
    say("CLEAN: done")
    return 0


# --- prerequisites ----------------------------------------------------------

def have_sdl2() -> bool:
    if WINDOWS:
        gcc = shutil.which("gcc")
        return bool(gcc) and (Path(gcc).parent / "SDL2.dll").is_file()
    if shutil.which("pkg-config"):
        if subprocess.run(["pkg-config", "--exists", "sdl2"]).returncode == 0:
            return True
    return bool(shutil.which("sdl2-config"))


def check_prerequisites() -> list[tuple[str, str]]:
    missing = []
    if sys.version_info < (3, 9):
        missing.append((f"Python 3.9 or newer (found {sys.version.split()[0]})",
                        "runs the ROM validator and the code generator"))
    if not (shutil.which("gcc") or (not WINDOWS and shutil.which("cc"))):
        missing.append(("C compiler (gcc)", "compiles the generated C and the game"))
    if not shutil.which("cmake"):
        missing.append(("CMake", "configures the build"))
    if not (shutil.which("ninja") or (not WINDOWS and shutil.which("make"))):
        missing.append(("Ninja", "runs the build"))
    if not have_sdl2():
        missing.append(("SDL2 development files", "window, audio and controller support"))
    return missing


def prerequisite_help() -> list[str]:
    if WINDOWS:
        return ["Install them with:",
                "    setup_windows.bat --install-deps",
                "then run setup again:",
                "    setup_windows.bat C:\\path\\to\\rom.sfc",
                "See docs\\BUILD_WINDOWS.md for details."]
    return ["Install them with the command for your distribution:",
            "    Debian / Ubuntu:  sudo apt install build-essential cmake ninja-build pkg-config libsdl2-dev python3",
            "    Fedora:           sudo dnf install gcc cmake ninja-build pkgconf-pkg-config SDL2-devel python3",
            "    Arch:             sudo pacman -S --needed base-devel cmake ninja sdl2 python",
            "then run setup again:",
            "    ./setup_linux.sh /path/to/rom.sfc"]


# --- ROM --------------------------------------------------------------------

def find_rom(arg: str | None) -> tuple[Path | None, list[str]]:
    if arg:
        p = Path(arg).expanduser()
        if p.is_file():
            return p, []
        return None, [f"ROM file not found: {arg}"]
    found = []
    for d in (REPO, REPO / "rom"):
        if d.is_dir():
            found += sorted(p for p in d.iterdir()
                            if p.is_file() and p.suffix.lower() in ROM_SUFFIXES)
    if len(found) == 1:
        return found[0], []
    if not found:
        return None, ["No ROM given.", "Pass the path to your Goof Troop (USA) ROM:",
                      f"    {SETUP_CMD} {ROM_EXAMPLE}",
                      "or copy it into this folder (it is ignored by git) and run setup again."]
    return None, ["More than one ROM file found:"] + [f"    {p}" for p in found] + \
                 ["Pass the one to use:", f"    {SETUP_CMD} <path to ROM>"]


# --- bundle -----------------------------------------------------------------

def pe_imports(objdump: str, binary: Path) -> list[str]:
    # objdump translates its labels ("DLL Name:"), so force the C locale and
    # match the value rather than the label.
    env = dict(os.environ, LC_ALL="C", LANGUAGE="C", LANG="C")
    r = subprocess.run([objdump, "-p", str(binary)], capture_output=True, text=True,
                       errors="replace", env=env)
    return [m.group(1) for m in (re.search(r"DLL[^:]*:\s*(\S+\.dll)\s*$", line, re.IGNORECASE)
                                 for line in r.stdout.splitlines()) if m]


def bundle_dlls(exe: Path, dll_dir: Path, dist: Path, objdump: str | None) -> list[str]:
    """Copy SDL2.dll and every other DLL the player imports that lives in the
    compiler's bin directory (i.e. is not a Windows system DLL), recursively,
    so dist/ runs without the toolchain on PATH."""
    copied, todo = [], ["SDL2.dll"]
    seen = set()
    if objdump:
        todo += pe_imports(objdump, exe)
    while todo:
        name = todo.pop()
        if name.lower() in seen:
            continue
        seen.add(name.lower())
        src = dll_dir / name
        if not src.is_file():
            continue                       # system DLL (or absent): not bundled
        shutil.copyfile(src, dist / src.name)
        copied.append(src.name)
        if objdump:
            todo += pe_imports(objdump, src)
    return sorted(copied)


def make_dist() -> tuple[int, list[str]]:
    for required in (BUILT_EXE, CANONICAL):
        if not required.is_file():
            return fail(EXIT_BUNDLE, "build output missing", [str(required)]), []
    err = remove_generated(DIST, (EXE_NAME, "canonical.sfc", LAUNCHER))
    if err:
        return fail(EXIT_CLEAN, "cannot refresh dist/", [err]), []
    DIST.mkdir()
    files = [EXE_NAME, "canonical.sfc", LAUNCHER]
    shutil.copyfile(BUILT_EXE, DIST / EXE_NAME)
    shutil.copyfile(CANONICAL, DIST / "canonical.sfc")
    if WINDOWS:
        gcc = shutil.which("gcc")
        dlls = bundle_dlls(DIST / EXE_NAME, Path(gcc).parent, DIST, shutil.which("objdump"))
        if "SDL2.dll" not in dlls:
            return fail(EXIT_BUNDLE, "SDL2.dll not found next to the compiler",
                        prerequisite_help()), []
        files += dlls
        (DIST / LAUNCHER).write_text(RUN_BAT, encoding="ascii", newline="\r\n")
    else:
        (DIST / LAUNCHER).write_text(RUN_SH, encoding="ascii", newline="\n")
        for name in (EXE_NAME, LAUNCHER):
            p = DIST / name
            p.chmod(p.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return 0, files


# --- main -------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        prog=SETUP_CMD,
        description="Validate your ROM, generate the game code, build it and prepare dist/.")
    ap.add_argument("rom", nargs="?", help="path to your Goof Troop (USA) ROM (only read)")
    ap.add_argument("--clean", action="store_true", help="remove build/ and dist/ and exit")
    ap.add_argument("--jobs", type=int, default=os.cpu_count() or 1, help="parallel build jobs")
    a = ap.parse_args(argv)

    if a.clean:
        return clean()

    say("== Goof Troop Recomp setup ==")
    say("[1/4] Checking prerequisites")
    missing = check_prerequisites()
    if missing:
        return fail(EXIT_PREREQ, "missing prerequisites",
                    [f"- {name}: {why}" for name, why in missing] + [""] + prerequisite_help())

    say("[2/4] Checking the ROM")
    rom, problem = find_rom(a.rom)
    if rom is None:
        return fail(EXIT_ROM, "ROM", problem)
    import validate_rom  # noqa: E402
    rc = validate_rom.main([str(rom)])
    if rc:
        return fail(rc, "this file is not the supported ROM",
                    ["Supported: Goof Troop (USA), 524288 bytes (a 512-byte copier header is accepted),",
                     "SHA-256 2bb368c47189ce813ad716eef16c01cd47685cb98e2c1cb35fa6f0173c97dd7c."])

    say("[3/4] Generating the game code from your ROM and building (a few minutes)")
    err = remove_generated(BUILD, ("generated", "cmake", "host-tests", "gates"))
    if err:
        return fail(EXIT_CLEAN, "cannot start a fresh build", [err])
    import goof_build  # noqa: E402
    rc = goof_build.main(["--rom", str(rom), "--build-dir", str(BUILD), "--jobs", str(max(1, a.jobs))])
    if rc:
        return fail(rc, "generation or build failed",
                    ["The messages above show the step that failed.",
                     "See docs/BUILD_WINDOWS.md or docs/BUILD_LINUX.md (Troubleshooting)."])

    say("\n[4/4] Preparing dist/")
    rc, files = make_dist()
    if rc:
        return rc
    for name in files:
        say(f"  dist/{name}")
    say("\nBuild complete.")
    say("Run:")
    say("  dist\\run_game.bat" if WINDOWS else "  ./run_game.sh")
    say("Press F2 in the game for Settings.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
